version: 2.1

orbs:
  slack: circleci/slack@4.4.0

jobs:
  build-net:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: Register Source
          command: dotnet nuget add source -n WIFIPLUG $MYGET_SOURCE
          working_directory: src/WifiPlug.Api
      - run:
          name: Build Solution
          command: dotnet build -c Release
      - run:
          name: Push API client to MyGet
          command: dotnet nuget push *.nupkg --api-key $MYGET_API_KEY --source $MYGET_SOURCE
          working_directory: src/WifiPlug.Api/bin/Release
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  main:
    jobs:
    - build-net:
        context:
            - Slack
            - MyGet
        filters:
            branches:
                only:
                - master
                - develop